name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: yunjae2295/haru-cote
          stage: main
          yaml: |
            name: haru-cote-server
            app: node@16
            options:
              env:
                - name: NODE_ENV
                  value: production
                - name: PROD_DB_USER
                  secret: PROD_DB_USER
                - name: PROD_DB_HOST
                  secret: PROD_DB_HOST
                - name: PROD_DB_DATABASE
                  secret: PROD_DB_DATABASE
                - name: PROD_DB_PASSWORD
                  secret: PROD_DB_PASSWORD     
                - name: PROD_DB_PORT
                  value: PROD_DB_PORT     
                - name: PROD_DOMAIN
                  value: PROD_DOMAIN
              ports: "3080"
              install: yarn
              build: yarn build
              start: yarn start
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
